package com.mediafever.service;

import org.apache.http.Header;
import org.apache.http.HttpResponse;
import org.apache.http.client.HttpClient;
import android.util.Log;
import com.jdroid.android.exception.CommonErrorCode;
import com.jdroid.android.exception.InvalidApiVersionException;
import com.jdroid.android.exception.InvalidUserTokenException;
import com.jdroid.java.exception.ErrorCode;
import com.jdroid.java.http.HttpWebServiceProcessor;
import com.jdroid.java.http.WebService;
import com.mediafever.android.AndroidErrorCode;

public class HttpResponseValidator implements HttpWebServiceProcessor {
	
	private static final String TAG = HttpResponseValidator.class.getSimpleName();
	
	private static final String STATUS_CODE_HEADER = "status-code";
	private static final String SUCCESSFULL_STATUS_CODE = "200";
	
	private static final HttpResponseValidator INSTANCE = new HttpResponseValidator();
	
	private HttpResponseValidator() {
		// nothing...
	}
	
	public static HttpResponseValidator get() {
		return INSTANCE;
	}
	
	/**
	 * @see com.jdroid.java.http.HttpWebServiceProcessor#beforeExecute(com.jdroid.java.http.WebService)
	 */
	@Override
	public void beforeExecute(WebService webService) {
		// Do Nothing
		
	}
	
	/**
	 * @see com.jdroid.java.http.HttpWebServiceProcessor#afterExecute(com.jdroid.java.http.WebService,
	 *      org.apache.http.client.HttpClient, org.apache.http.HttpResponse)
	 */
	@Override
	public void afterExecute(WebService webService, HttpClient client, HttpResponse httpResponse) {
		// validate response.
		this.validateResponse(httpResponse);
	}
	
	/**
	 * Validate the response generated by the server.
	 * 
	 * @param httpResponse
	 */
	protected void validateResponse(HttpResponse httpResponse) {
		
		String message = logStatusCode(httpResponse);
		if (isSuccess(httpResponse)) {
			ErrorCode errorCode = getErrorCode(httpResponse, CommonErrorCode.SERVER_ERROR);
			if (errorCode != null) {
				throw errorCode.newBusinessException();
			}
			
		} else if (isClientError(httpResponse)) {
			ErrorCode errorCode = getErrorCode(httpResponse, CommonErrorCode.INTERNAL_ERROR);
			if (CommonErrorCode.INVALID_API_VERSION.equals(errorCode)) {
				throw new InvalidApiVersionException();
			} else if (CommonErrorCode.INVALID_USER_TOKEN.equals(errorCode)) {
				throw new InvalidUserTokenException();
			} else if (AndroidErrorCode.INVALID_CREDENTIALS.equals(errorCode)) {
				throw AndroidErrorCode.INVALID_CREDENTIALS.newBusinessException();
			}
		} else if (isServerError(httpResponse)) {
			throw CommonErrorCode.SERVER_ERROR.newApplicationException(message);
		}
	}
	
	private String logStatusCode(HttpResponse httpResponse) {
		int code = httpResponse.getStatusLine().getStatusCode();
		StringBuilder sb = new StringBuilder();
		sb.append("HTTP Status code: ");
		sb.append(code);
		sb.append(" Reason: ");
		sb.append(httpResponse.getStatusLine().getReasonPhrase());
		if (isSuccess(httpResponse)) {
			Log.d(TAG, sb.toString());
		} else {
			Log.w(TAG, sb.toString());
		}
		return sb.toString();
	}
	
	private Boolean isSuccess(HttpResponse httpResponse) {
		int code = httpResponse.getStatusLine().getStatusCode();
		return (code >= 200) && (code <= 299);
	}
	
	private Boolean isClientError(HttpResponse httpResponse) {
		int code = httpResponse.getStatusLine().getStatusCode();
		return (code >= 400) && (code <= 499);
	}
	
	private Boolean isServerError(HttpResponse httpResponse) {
		int code = httpResponse.getStatusLine().getStatusCode();
		return (code >= 500) && (code <= 599);
	}
	
	private ErrorCode getErrorCode(HttpResponse httpResponse, ErrorCode defaultErrorCode) {
		ErrorCode errorCode = null;
		Header[] headerstatusCode = httpResponse.getHeaders(STATUS_CODE_HEADER);
		if (headerstatusCode.length > 0) {
			String statusCode = headerstatusCode[0].getValue();
			Log.d(TAG, "Server Status code: " + statusCode);
			if (!statusCode.equals(SUCCESSFULL_STATUS_CODE)) {
				errorCode = AndroidErrorCode.findByStatusCode(statusCode);
				if (errorCode == null) {
					errorCode = CommonErrorCode.findByStatusCode(statusCode);
					if (errorCode == null) {
						Log.w(TAG, "Unknown Server Status code: " + statusCode);
						throw defaultErrorCode.newApplicationException("Unknown Server Status code: " + statusCode);
					}
				}
			}
		} else {
			throw CommonErrorCode.SERVER_ERROR.newApplicationException("Missing " + STATUS_CODE_HEADER + " header.");
		}
		return errorCode;
	}
}
